name: OIDC Forensic Capture

on: [push]

jobs:
  capture-exchange:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Perform OIDC Exchange
        run: |
          curl -v -X POST \
          "$ACTIONS_ID_TOKEN_REQUEST_URL" \
          -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"audience": "https://github.com/dustinmac2744"}'

